from django.urls import path

from .views import (
    AddDeviceToGroupView,
    DeregisterFCMDeviceView,
    HealthView,
    CreateGroupKeyEnvelopeView,
    CreateGroupView,
    CreateDeviceAuthChallengeView,
    CreateDeviceAuthTokenView,
    DeleteEncryptedImageView,
    DeleteGroupView,
    DownloadEncryptedImageBlobView,
    GetDeviceGroupKeyEnvelopesView,
    DeviceLeavesGroupView,
    GetDeviceGroupsView,
    ListEncryptedImagesView,
    GetOwnGroupDevicesView,
    GetManagerGroupsView,
    ListGroupDevicesView,
    GetDeviceSelfStatusView,
    NotifyGroupView,
    RegisterDeviceView,
    RegisterFCMDeviceView,
    RemoveDeviceFromGroupView,
    RevokeDeviceAuthTokenView,
    UpdateGroupView,
    UploadEncryptedImageView,
    LogoutView,
    GetMainManagerGroupsView,
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path(
        'status/',
        HealthView.as_view(),
        name='health',
    ),
    path(
        'device/fcm/',
        RegisterFCMDeviceView.as_view(),
        name='device-fcm-register',
    ),
    path(
        'device/fcm/deregister/',
        DeregisterFCMDeviceView.as_view(),
        name='device-fcm-deregister',
    ),
    path(
        'device/auth/challenge/',
        CreateDeviceAuthChallengeView.as_view(),
        name='device-auth-challenge',
    ),
    path(
        'device/auth/token/',
        CreateDeviceAuthTokenView.as_view(),
        name='device-auth-token',
    ),
    path(
        'device/auth/revoke/',
        RevokeDeviceAuthTokenView.as_view(),
        name='device-auth-revoke',
    ),
    path(
        'device/groups/',
        GetDeviceGroupsView.as_view(),
        name='device-groups',
    ),
    path(
        'device/self/status/',
        GetDeviceSelfStatusView.as_view(),
        name='device-self-status',
    ),
    path(
        'device/leave-group/',
        DeviceLeavesGroupView.as_view(),
        name='device-leave-group',
    ),
    path(
        'device/group-key-envelopes/',
        GetDeviceGroupKeyEnvelopesView.as_view(),
        name='device-group-key-envelopes',
    ),
    path(
        'device/encrypted-images/',
        ListEncryptedImagesView.as_view(),
        name='device-encrypted-images',
    ),
    path(
        'device/encrypted-images/<uuid:image_uuid>/blob/',
        DownloadEncryptedImageBlobView.as_view(),
        name='device-encrypted-image-blob',
    ),
    path(
        'manager/upload-encrypted-blob/',
        UploadEncryptedImageView.as_view(),
        name='upload-encrypted-blob',
    ),
    path(
        'manager/notify-group/',
        NotifyGroupView.as_view(),
        name='manager-notify-group',
    ),
    path(
        'manager/groups/',
        GetManagerGroupsView.as_view(),
        name='manager-groups',
    ),
    path(
        'manager/group-devices/',
        GetOwnGroupDevicesView.as_view(),
        name='manager-group-devices',
    ),
    path(
        'delete-encrypted-image/',
        DeleteEncryptedImageView.as_view(),
        name='delete-encrypted-image',
    ),
    path(
        'main-manager/register-device/',
        RegisterDeviceView.as_view(),
        name='register-device',
    ),
    path(
        'main-manager/create-group/',
        CreateGroupView.as_view(),
        name='create-group',
    ),
    path(
        'main-manager/create-group-key-envelope/',
        CreateGroupKeyEnvelopeView.as_view(),
        name='create-group-key-envelope',
    ),
    path(
        'main-manager/update-group/',
        UpdateGroupView.as_view(),
        name='update-group',
    ),
    path(
        'main-manager/delete-group/',
        DeleteGroupView.as_view(),
        name='delete-group',
    ),
    path(
        'main-manager/add-device-to-group/',
        AddDeviceToGroupView.as_view(),
        name='add-device-to-group',
    ),
    path(
        'main-manager/remove-device-from-group/',
        RemoveDeviceFromGroupView.as_view(),
        name='remove-device-from-group',
    ),
    path(
        'main-manager/groups/',
         GetMainManagerGroupsView.as_view(),
         name='main-manager-groups'
    ),
    path(
        'main-manager/group-devices/',
        ListGroupDevicesView.as_view(),
        name='main-manager-group-devices',
    ),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("token/logout/", LogoutView.as_view(), name="token_logout")
]
