# Generated by Django 6.0.3 on 2026-05-06 05:55

import django.db.models.deletion
import eyesonly.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FCM_DJANGO_FCMDEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_name', models.TextField()),
                ('crypto_version', models.PositiveSmallIntegerField(default=1)),
                ('encryption_algorithm', models.CharField(default='xchacha20poly1305', max_length=32)),
                ('name_nonce', models.BinaryField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('public_key_algorithm', models.CharField(default='x25519', max_length=32)),
                ('public_key_fingerprint', models.CharField(max_length=64)),
                ('fcm_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyesonly_device', to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.device')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_blob', models.FileField(storage=eyesonly.models.EncryptedImageStorage(), upload_to=eyesonly.models.get_encrypted_blob_upload_path)),
                ('encrypted_caption', models.TextField(null=True)),
                ('crypto_version', models.PositiveSmallIntegerField(default=1)),
                ('encryption_algorithm', models.CharField(default='xchacha20poly1305', max_length=32)),
                ('payload_nonce', models.BinaryField(max_length=24, null=True)),
                ('ciphertext_hash_sha256', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(default=eyesonly.models.default_encrypted_image_expires_at, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_encrypted_images', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.group')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main_manager', 'Main manager'), ('manager', 'Manager')], max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.group')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('manager', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='managers',
            field=models.ManyToManyField(related_name='eyesonly_groups', through='eyesonly.ManagerRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeviceAuthChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.device')),
            ],
            options={
                'unique_together': {('device', 'challenge_hash')},
            },
        ),
        migrations.CreateModel(
            name='GroupDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_member_name', models.TextField(blank=True, null=True)),
                ('can_delete_images', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyesonly.group')),
            ],
            options={
                'unique_together': {('group', 'device')},
            },
        ),
        migrations.CreateModel(
            name='GroupKeyEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('group_shared', 'Group shared'), ('manager_roster', 'Manager roster')], default='group_shared', max_length=32)),
                ('key_wrap_algorithm', models.CharField(default='x25519-hkdf-xchacha20poly1305', max_length=32)),
                ('recipient_key_fingerprint', models.CharField(max_length=64)),
                ('encrypted_group_key', models.BinaryField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='eyesonly.group')),
                ('recipient_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_key_envelopes', to='eyesonly.device')),
            ],
            options={
                'unique_together': {('group', 'recipient_device', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='RecipientEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_wrap_algorithm', models.CharField(default='x25519-hkdf-xchacha20poly1305', max_length=32)),
                ('recipient_key_fingerprint', models.CharField(max_length=64)),
                ('encrypted_content_key', models.BinaryField()),
                ('encrypted_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_envelopes', to='eyesonly.encryptedimage')),
                ('recipient_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_envelopes', to='eyesonly.device')),
            ],
            options={
                'unique_together': {('encrypted_image', 'recipient_device')},
            },
        ),
    ]
