# Generated by Django 6.0.3 on 2026-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyesonly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_devices',
            field=models.PositiveIntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_groups',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_images',
            field=models.PositiveIntegerField(default=50, null=True),
        ),
    ]
